apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: {{ include "mongodb-chart.fullname" . }}-mongodb

spec:
  serviceName: {{ include "mongodb-chart.fullname" . }}-mongodb-headless

  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: mongodb

  template:
    metadata:
      labels:
        app: mongodb

    spec:
      containers:
        - name: mongodb
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.containerPort }}

          volumeMounts:
            - name: mongodb-storage
              mountPath: /data/db

  volumeClaimTemplates:
    - metadata:
        name: mongodb-storage
      spec:
        accessModes:
          - {{ .Values.persistence.accessMode }}
        storageClassName: {{ .Values.persistence.storageClass }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}