apiVersion: v1
kind: Secret

metadata:
  name: backend-secret

type: Opaque

stringData:
  JWT_SECRET: 8b7f9d3a1c5e8f4b7d2a9e6c3f1b8d5e4a7c9f2d6e1b3a8f5c7d9e2a4b6f8c1d3e5a7b9c2d4f6e8a1b3c5d7f9e2a4c6
  