apiVersion: v1
kind: Service

metadata:
  name: {{ include "proshop-chart.fullname" . }}-backend-service

spec:
  selector:
    app: backend

  ports:
    # - port: 5000
    #   targetPort: 5000
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.containerPort}}

  # type: ClusterIP 

  type: {{ .Values.backend.service.type }}
         