apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "proshop-chart.fullname" . }}-config

data: 
  # MONGO_URI: mongodb://mongodb-service:27017/proshop
  # NODE_ENV: development
  # PORT: "5000"
  # #JWT_SECRET: 8b7f9d3a1c5e8f4b7d2a9e6c3f1b8d5e4a7c9f2d6e1b3a8f5c7d9e2a4b6f8c1d3e5a7b9c2d4f6e8a1b3c5d7f9e2a4c6

  # PAYPAL_CLIENT_ID: test

  # PAYPAL_APP_SECRET: test

  # PAYPAL_API_URL: https://api-m.sandbox.paypal.com

  # MONGO_URI: mongodb://{{ include "proshop-chart.fullname" . }}-mongodb-headless:27017/proshop
  MONGO_URI: mongodb://{{ .Release.Name }}-mongodb-chart-mongodb-headless:27017/proshop
  NODE_ENV: {{ .Values.backend.config.nodeEnv }}
  PORT: {{ .Values.backend.config.port | quote }}
  PAYPAL_CLIENT_ID: {{ .Values.backend.config.paypalClientId }}
  PAYPAL_APP_SECRET: {{ .Values.backend.config.paypalAppSecret }}
  PAYPAL_API_URL: {{ .Values.backend.config.paypalApiUrl }}

